---
abstract: 'The great new App::DiFm::GetPlaylists!'
author:
  - 'Ben Kolera, C<< <ben.kolera at gmail.com> >>'
  - 'Ben Kolera <ben.kolera@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-DiFm-GetPlaylists
no_index:
  directory:
    - inc
    - t
requires:
  Getopt::Long: 0
  JSON: 0
  Pod::Usage: 0
  WWW::Mechanize: 0
  autodie: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
